#!/usr/bin/env ansible-playbook
---
- import_playbook: provisioning.yml
  tags: provisioning
- import_playbook: bigbluebutton.yml
  tags: bigbluebutton
- import_playbook: scalelite.yml
  tags: scalelite
- import_playbook: greenlight.yml
  tags: greenlight
- import_playbook: monitoring.yml
  tags: monitoring
